# Custom Language File for Launcher Customizer

[ejs.app]
title = "ZLauncher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Lord-ZuzurNC/ZLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/kyNBTDaZsU"

[ejs.settings]
sourceGithubLink = "https://github.com/Lord-ZuzurNC/ZLauncher"
supportLink = "https://github.com/Lord-ZuzurNC/ZLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO ZCMCS!"
welcomeDescription = "This is ZCMCS, which stands for ZCastle MineCraft Server.  This server is entirely modded at a point that will highly affect user experience based on Vanilla experience.  It adds not only Blocks and Enteity but also Gameplay, Biomes and UI/UX."
welcomeDescCTA = "You are just a few clicks away from entering in the ZCMCS server."
